version: '2'

services:
    php:
        container_name: php
        build: .
        volumes:
            - ./www:/var/www/
    web:
        image: nginx:1.15.0
        container_name: webserver
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    mysql:
        image: bitnami/mariadb
        container_name: mariadb
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - ./mariadb/data/mysql:/bitnami
        environment:
          MARIADB_ROOT_PASSWORD: root
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      links:
        - mysql
      environment:
        PMA_HOST: mariadb
        PMA_PORT: 3306
      ports:
        - 8181:80
      volumes:
        - ./phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php
