version: '2'

services:
    php:
        container_name: php
        build: .
        volumes:
            - ./www:/var/www/
        networks:
            - code-network
    web:
        image: nginx:latest
        container_name: webserver
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            code-network:
              ipv4_address: 172.25.0.101
        links:
            - php
    mysql:
        image: mariadb:latest
        container_name: mariadb
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
          -MYSQL_ROOT_PASSWORD: root
        networks:
            code-network:
              ipv4_address: 172.25.0.100
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      links:
        - mysql:mariadb
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
      ports:
        - 8181:80
      networks:
          - code-network

networks:
    code-network:
        driver: bridge
        ipam:
          config:
          - subnet: 172.25.0.0/24
